import { useEffect, useState } from 'react'
import { ArrowLeft, ChevronDown, Send, X } from 'lucide-react'
import { getAcademicBatchReport, listAcademicReportBatches, listFacultyAcademicReportTests, sendAcademicTestReport } from '../services/academicTestService'
import '../styles/AcademicTestReportPage.css'
import '../styles/AcademicTestReportPercent.css'
import '../styles/AcademicTestReportLayout.css'
import '../styles/AcademicTestReportLayoutTight.css'

const value = (item, fallback = '-') => item === null || item === undefined || item === '' ? fallback : item
const resultClass = (result) => String(result || '').toLowerCase() === 'pass' ? 'is-pass' : String(result || '').toLowerCase() === 'fail' ? 'is-fail' : ''

function Attempt({ attempt }) { return <div className="academic-report-attempt"><span>{attempt.attemptType === 'RETEST' ? `Retest ${attempt.attemptNumber || ''}` : 'Original'}</span><strong>{attempt.status === 'SUBMITTED' ? `${attempt.marksObtained}/${attempt.totalMarks}` : attempt.status === 'NOT_ATTENDED' ? 'Not Attended' : 'Not Submitted'}</strong>{attempt.percentage !== null && <small>{attempt.percentage}%</small>}<em className={resultClass(attempt.result)}>{value(attempt.result, '')}</em></div> }
function TestCell({ test }) { const [open, setOpen] = useState(false); const final = test.final || {}; return <div className="academic-report-test-cell"><div className="academic-report-final"><strong>{final.status === 'SUBMITTED' ? `${final.marksObtained}/${final.totalMarks}` : final.status === 'NOT_ATTENDED' ? 'Not Attended' : '-'}</strong>{final.percentage !== null && final.percentage !== undefined && <small className="academic-report-cell-percent">{final.percentage}%</small>}<em className={resultClass(final.result)}>{value(final.result)}</em></div>{test.attempts?.length > 1 && <><button type="button" className="academic-report-history-toggle" onClick={() => setOpen(!open)}>{open ? 'Hide history' : `${test.attempts.length} attempts`}<ChevronDown size={14} className={open ? 'is-open' : ''} /></button>{open && <div className="academic-report-history">{test.attempts.map((attempt) => <Attempt key={attempt.scheduleId} attempt={attempt} />)}</div>}</>}</div> }

export default function AcademicTestReportPage({ embedded = false }) {
  const [batches, setBatches] = useState([]); const [batchSearch, setBatchSearch] = useState(''); const [batchPage, setBatchPage] = useState(1); const [report, setReport] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [sendOpen, setSendOpen] = useState(false); const [sendBatchId, setSendBatchId] = useState(''); const [sendTests, setSendTests] = useState([]); const [selectedSendTests, setSelectedSendTests] = useState([]); const [sendLoading, setSendLoading] = useState(false); const [sendMessage, setSendMessage] = useState('')
  const loadBatches = async () => { try { setLoading(true); setBatches(await listAcademicReportBatches()) } catch (err) { setError(err.message || 'Unable to load report batches.') } finally { setLoading(false) } }
  useEffect(() => { loadBatches() }, [])
  const openBatch = async (batchId) => { try { setError(''); setLoading(true); setReport(await getAcademicBatchReport(batchId)) } catch (err) { setError(err.message || 'Unable to load student report.') } finally { setLoading(false) } }
  const openSend = async () => { setSendOpen(true); setSendMessage(''); setSendBatchId(''); setSendTests([]); setSelectedSendTests([]); try { await loadBatches() } catch {} }
  const selectSendBatch = async (batchId) => { setSendBatchId(batchId); setSelectedSendTests([]); if (!batchId) return setSendTests([]); try { setSendLoading(true); setSendTests(await listFacultyAcademicReportTests(batchId)) } catch (err) { setSendMessage(err.message || 'Unable to load completed tests.') } finally { setSendLoading(false) } }
  const submitSend = async () => { if (!sendBatchId || !selectedSendTests.length) return setSendMessage('Select a batch and at least one completed test.'); try { setSendLoading(true); await sendAcademicTestReport({ batchId: sendBatchId, academicTestIds: selectedSendTests }); setSendOpen(false); setSuccess('Academic test report sent to the Branch Admin.') } catch (err) { setSendMessage(err.message || 'Unable to send report.') } finally { setSendLoading(false) } }
  const tests = report?.tests || []; const hasProject = Boolean(report?.hasProject); const matchingBatches = batches.filter((batch) => { const query = batchSearch.trim().toLowerCase(); return !query || [batch.batchId, batch.batchName].some((item) => String(item || '').toLowerCase().includes(query)) }); const batchPageCount = Math.max(1, Math.ceil(matchingBatches.length / 5)); const filteredBatches = matchingBatches.slice((batchPage - 1) * 5, batchPage * 5)
  useEffect(() => { setBatchPage(1) }, [batchSearch]); useEffect(() => { if (batchPage > batchPageCount) setBatchPage(batchPageCount) }, [batchPage, batchPageCount])
  useEffect(() => { if (report || batchPageCount <= 1) return undefined; const card = document.querySelector('.academic-report-page .academic-report-card'); const tableWrap = card?.querySelector('.academic-report-table-wrap'); if (!tableWrap || card.querySelector('.academic-report-pagination')) return undefined; const pagination = document.createElement('div'); pagination.className = 'academic-report-pagination'; const render = () => { pagination.innerHTML = ''; const previous = document.createElement('button'); previous.textContent = 'Previous'; previous.disabled = batchPage <= 1; previous.onclick = () => setBatchPage((page) => Math.max(1, page - 1)); pagination.appendChild(previous); for (let page = 1; page <= batchPageCount; page += 1) { const button = document.createElement('button'); button.textContent = String(page); button.className = page === batchPage ? 'is-active' : ''; button.onclick = () => setBatchPage(page); pagination.appendChild(button) } const next = document.createElement('button'); next.textContent = 'Next'; next.disabled = batchPage >= batchPageCount; next.onclick = () => setBatchPage((page) => Math.min(batchPageCount, page + 1)); pagination.appendChild(next) }; render(); tableWrap.after(pagination); return () => pagination.remove() }, [report, batchPage, batchPageCount, filteredBatches.length])
  return <main className={`academic-report-page ${embedded ? 'is-embedded' : ''}`}>
    <div className="academic-report-heading"><div><p className="academic-report-kicker">FACULTY WORKSPACE</p><h1>Academic Test Report</h1><p>Review final test attempts, retest history and project performance by batch.</p></div><div className="academic-report-heading-actions">{!report && <button type="button" className="academic-report-primary academic-report-send-button" onClick={openSend}><Send size={16} /> Send Report</button>}{report && <button type="button" className="academic-report-back" onClick={() => setReport(null)}><ArrowLeft size={16} /> All batches</button>}</div></div>
    {error && <div className="academic-report-error">{error}</div>}{success && <div className="academic-report-success">{success}</div>}
    {!report ? <section className="academic-report-card"><div className="academic-report-card-title"><div><h2>Batch Reports</h2><input className="academic-report-search" value={batchSearch} onChange={(event) => setBatchSearch(event.target.value)} placeholder="Search Batch ID or Batch Name" /></div><span>{filteredBatches.length} batches</span></div><div className="academic-report-table-wrap"><table className="academic-report-table"><thead><tr><th>Batch ID</th><th>Batch Name</th><th>Course</th><th>Total Tests</th><th>Batch Timing</th><th>Action</th></tr></thead><tbody>{loading ? <tr><td colSpan="6">Loading reports...</td></tr> : filteredBatches.length ? filteredBatches.map((batch) => <tr key={batch.id}><td>{batch.batchId}</td><td>{batch.batchName}</td><td>{batch.course?.name || batch.courseName}</td><td>{batch.totalTests}</td><td>{value(batch.batchTiming)}</td><td><button type="button" className="academic-report-primary" onClick={() => openBatch(batch.id)}>View Students</button></td></tr>) : <tr><td colSpan="6">No matching batches available.</td></tr>}</tbody></table></div></section> : <section className="academic-report-card"><div className="academic-report-card-title"><div><h2>{report.batch.batchName}</h2><p>{report.batch.batchId} · {report.course?.name || '-'} · {value(report.batch.batchTiming)}</p></div><span>{report.students?.length || 0} students</span></div><div className="academic-report-table-wrap"><table className="academic-report-table academic-report-student-table"><thead><tr><th>Student</th><th>Student ID</th>{tests.map((test) => <th key={test.testNumber}>Test {test.testNumber}</th>)}{hasProject && <th>Project</th>}<th>Overall Test %</th>{hasProject && <th>Overall Project %</th>}</tr></thead><tbody>{loading ? <tr><td colSpan={tests.length + 4}>Loading...</td></tr> : report.students?.length ? report.students.map((row) => <tr key={row.student.id}><td><strong>{row.student.studentName}</strong><small>{row.student.emailAddress}</small></td><td>{row.student.studentId}</td>{row.tests.map((test) => <td key={test.testNumber}><TestCell test={test} /></td>)}{hasProject && <td><div className="academic-report-final"><strong>{row.project?.marksAwarded == null ? '-' : `${row.project.marksAwarded}/${row.project.totalMarks}`}</strong><em className={resultClass(row.project?.result)}>{value(row.project?.result)}</em></div></td>}<td className="academic-report-percent">{row.overallTestPercentage == null ? '-' : `${row.overallTestPercentage}%`}</td>{hasProject && <td className="academic-report-percent">{row.overallProjectPercentage == null ? '-' : `${row.overallProjectPercentage}%`}</td>}</tr>) : <tr><td colSpan={tests.length + 4}>No students found in this batch.</td></tr>}</tbody></table></div></section>}
    {sendOpen && <div className="academic-report-modal-backdrop"><section className="academic-report-send-modal"><div className="academic-report-send-heading"><div><p className="academic-report-kicker">FACULTY WORKSPACE</p><h2>Send Academic Test Report</h2></div><button type="button" onClick={() => setSendOpen(false)} aria-label="Close"><X size={18} /></button></div>{sendMessage && <div className="academic-report-error">{sendMessage}</div>}<label>Batch<select value={sendBatchId} onChange={(event) => selectSendBatch(event.target.value)}><option value="">Select batch</option>{batches.map((batch) => <option key={batch.id} value={batch.id}>{batch.batchName} ({batch.batchId})</option>)}</select></label><div className="academic-report-send-list"><strong>Completed tests</strong>{sendLoading ? <p>Loading...</p> : sendTests.length ? sendTests.map((test) => <label key={test.id} className="academic-report-send-check"><input type="checkbox" checked={selectedSendTests.includes(test.id)} onChange={() => setSelectedSendTests((current) => current.includes(test.id) ? current.filter((id) => id !== test.id) : [...current, test.id])} /><span>{test.label}</span><small>{test.testDate || ''}</small></label>) : <p>Select a batch to view completed tests.</p>}</div><div className="academic-report-send-actions"><button type="button" onClick={() => setSendOpen(false)}>Cancel</button><button type="button" className="academic-report-primary" onClick={submitSend} disabled={sendLoading || !selectedSendTests.length}>{sendLoading ? 'Sending...' : 'Send Report'}</button></div></section></div>}
  </main>
}
