import { useEffect, useMemo, useState } from 'react'
import { Search, RotateCcw, X, Send } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import { getFacultyExamReports, listFacultyAssessments, listFacultyExamBatches, listFacultyExamCourses, listFacultyExamModules, listFacultyTests, sendFacultyReport } from '../services/examService'
import '../styles/FacultyExamReports.css'
import FacultyAssessmentReportsPage from './FacultyAssessmentReportsPage'

function ReportsTabs({ active, navigate, onSend }) {
  return <div className="faculty-reports-tabs"><button type="button" className={active === 'tests' ? 'is-active' : ''} onClick={() => navigate('/dashboard/faculty/exams/reports')}>Test Reports</button><button type="button" className={active === 'assessments' ? 'is-active' : ''} onClick={() => navigate('/dashboard/faculty/exams/reports?tab=assessments')}>Assessment Reports</button><button type="button" className="exam-primary faculty-report-send-button" onClick={onSend}><Send size={15} /> Send Report</button></div>
}

function SendReportModal({ courses, modules, batches, courseId, facultyTests = [], facultyAssessments = [], onCourseChange, onClose, onSent }) {
  const [batchId, setBatchId] = useState(''); const [testModuleIds, setTestModuleIds] = useState([]); const [assessmentModuleIds, setAssessmentModuleIds] = useState([]); const [sending, setSending] = useState(false); const [error, setError] = useState('')
  const filteredBatches = batches
  const matchesCourse = (item) => (item.branchCourseId || item.branchCourse?.id || item.courseId || item.course?.id) === courseId
  const testModules = modules.filter((module) => facultyTests.some((test) => matchesCourse(test) && (test.moduleId || test.module?.id) === module.id && (test.schedules || []).some((schedule) => schedule.batchId === batchId)))
  const assessmentModules = modules.filter((module) => facultyAssessments.some((assessment) => matchesCourse(assessment) && (assessment.moduleId || assessment.module?.id) === module.id && (assessment.branchBatchId || assessment.branchBatch?.id || assessment.batchId) === batchId))
  const toggle = (setter, id) => setter((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const submit = async () => { if (!batchId || (!testModuleIds.length && !assessmentModuleIds.length)) { setError('Select one batch and at least one report module.'); return } setSending(true); setError(''); try { await sendFacultyReport({ batchId, testModuleIds, assessmentModuleIds }); onSent() } catch (e) { setError(e.message) } finally { setSending(false) } }
  return <div className="exam-modal-backdrop"><div className="exam-modal faculty-report-modal"><div className="exam-modal-header"><div><p className="exam-kicker">BRANCH ADMIN REPORT SHARING</p><h2>Send Report</h2></div><button type="button" className="exam-icon-button" onClick={onClose}><X size={20} /></button></div><div className="exam-modal-body"><label>Course<select value={courseId} onChange={(e) => { onCourseChange(e.target.value); setBatchId(''); setTestModuleIds([]); setAssessmentModuleIds([]) }}><option value="">Select course</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</select></label><label>Batch<select value={batchId} onChange={(e) => setBatchId(e.target.value)} disabled={!courseId}><option value="">Select one batch</option>{filteredBatches.map((batch) => <option key={batch.id} value={batch.id}>{batch.batchName || batch.batchId} ({batch.batchId})</option>)}</select></label><div className="faculty-report-module-groups"><fieldset><legend>Test Report modules</legend>{testModules.length ? testModules.map((module) => <label key={`test-${module.id}`}><input type="checkbox" checked={testModuleIds.includes(module.id)} onChange={() => toggle(setTestModuleIds, module.id)} />{module.title}</label>) : <p className="faculty-report-module-empty">Select a course to view modules.</p>}</fieldset><fieldset><legend>Assessment Report modules</legend>{assessmentModules.length ? assessmentModules.map((module) => <label key={`assessment-${module.id}`}><input type="checkbox" checked={assessmentModuleIds.includes(module.id)} onChange={() => toggle(setAssessmentModuleIds, module.id)} />{module.title}</label>) : <p className="faculty-report-module-empty">No assessments created for this batch.</p>}</fieldset></div>{error && <div className="exam-error">{error}</div>}</div><div className="exam-modal-footer"><button type="button" className="exam-secondary" onClick={onClose}>Cancel</button><button type="button" className="exam-primary" onClick={submit} disabled={sending}>{sending ? 'Sending...' : 'Send Report'}</button></div></div></div>
}

export function FacultyExamReportsPage({ embedded = false }) {
  const navigate = useNavigate()
  const location = useLocation()
  const assessmentTab = new URLSearchParams(location.search).get('tab') === 'assessments'
  const [courses, setCourses] = useState([]); const [modules, setModules] = useState([]); const [batches, setBatches] = useState([]); const [reports, setReports] = useState([]); const [facultyTests, setFacultyTests] = useState([]); const [facultyAssessments, setFacultyAssessments] = useState([])
  const [courseId, setCourseId] = useState(''); const [moduleId, setModuleId] = useState(''); const [batchId, setBatchId] = useState(''); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [shareOpen, setShareOpen] = useState(false); const [shareMessage, setShareMessage] = useState('')
  useEffect(() => { listFacultyExamCourses().then(setCourses).catch((e) => setError(e.message)) }, [])
  useEffect(() => { if (!shareOpen) return; Promise.all([listFacultyTests(), listFacultyAssessments()]).then(([testItems, assessmentItems]) => { setFacultyTests(testItems); setFacultyAssessments(assessmentItems) }).catch((e) => setError(e.message)) }, [shareOpen])
  useEffect(() => { if (!courseId) return; Promise.all([listFacultyExamModules(courseId), listFacultyExamBatches(courseId)]).then(([moduleItems, batchItems]) => { setModules(moduleItems); setBatches(batchItems) }).catch((e) => setError(e.message)) }, [courseId])
  useEffect(() => { getFacultyExamReports({ courseId, moduleId, batchId }).then(setReports).catch((e) => setError(e.message)).finally(() => setLoading(false)) }, [courseId, moduleId, batchId])
  const visibleReports = useMemo(() => { const query = search.trim().toLowerCase(); if (!query) return reports; return reports.filter((row) => [row.module?.title, row.batch?.name, row.batch?.batchId].some((value) => String(value || '').toLowerCase().includes(query))) }, [reports, search])
  const reset = () => { setCourseId(''); setModuleId(''); setBatchId(''); setSearch('') }
  const handleCourseChange = (value) => { setCourseId(value); setModuleId(''); setBatchId(''); setModules([]); setBatches([]) }
  const tabs = <ReportsTabs active={assessmentTab ? 'assessments' : 'tests'} navigate={navigate} onSend={() => { setShareMessage(''); setShareOpen(true) }} />
  if (assessmentTab) return <section className="exam-reports-page">{tabs}{shareMessage && <div className="exam-success">{shareMessage}</div>}<FacultyAssessmentReportsPage embedded />{shareOpen && <SendReportModal courses={courses} modules={modules} batches={batches} courseId={courseId} facultyTests={facultyTests} facultyAssessments={facultyAssessments} onCourseChange={handleCourseChange} onClose={() => setShareOpen(false)} onSent={() => { setShareOpen(false); setShareMessage('Report sent to Branch Admin successfully.') }} />}</section>
  return <section className={`exam-reports-page ${embedded ? 'exam-page-embedded' : ''}`}>{tabs}{shareMessage && <div className="exam-success">{shareMessage}</div>}<div className="exam-reports-header"><div><p className="exam-kicker">FACULTY WORKSPACE</p><h1>Exam Reports</h1><p>View consolidated test performance by module and batch.</p></div></div><div className="exam-reports-filter-card"><label>Course<select value={courseId} onChange={(e) => handleCourseChange(e.target.value)}><option value="">All assigned courses</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</select></label><label>Module<select value={moduleId} onChange={(e) => setModuleId(e.target.value)} disabled={!courseId}><option value="">All modules</option>{modules.map((module) => <option key={module.id} value={module.id}>{module.title}</option>)}</select></label><label>Batch<select value={batchId} onChange={(e) => setBatchId(e.target.value)} disabled={!courseId}><option value="">All assigned batches</option>{batches.map((batch) => <option key={batch.id} value={batch.id}>{batch.batchName || batch.batchId}</option>)}</select></label><label className="exam-reports-search"><span>Search</span><div><Search size={16} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Module, batch or ID" /></div></label><button className="exam-secondary exam-reports-reset" onClick={reset}><RotateCcw size={15} /> Reset</button></div>{error && <div className="exam-error">{error}</div>}<div className="exam-card exam-reports-table-card"><div className="exam-card-heading"><h2>Consolidated reports</h2></div>{loading ? <p className="exam-muted">Loading exam reports...</p> : <div className="exam-table-wrap"><table><thead><tr><th>Module</th><th>Batch Name</th><th>Batch ID</th><th>Batch Timing</th><th>Tests</th><th>MCQs</th><th>Action</th></tr></thead><tbody>{visibleReports.length ? visibleReports.map((row) => <tr key={`${row.module.id}-${row.batch.id}`}><td><strong>{row.module.title}</strong></td><td>{row.batch.name || '-'}</td><td>{row.batch.batchId || '-'}</td><td>{row.batch.timing || '-'}</td><td>{row.testCount}</td><td>{row.mcqCount}</td><td><button className="exam-link" onClick={() => navigate(`/dashboard/faculty/exams/reports/${row.module.id}/${row.batch.id}`)}>View Student Report</button></td></tr>) : <tr><td colSpan="7" className="exam-empty">No exam reports found.</td></tr>}</tbody></table></div>}</div>{shareOpen && <SendReportModal courses={courses} modules={modules} batches={batches} courseId={courseId} facultyTests={facultyTests} facultyAssessments={facultyAssessments} onCourseChange={handleCourseChange} onClose={() => setShareOpen(false)} onSent={() => { setShareOpen(false); setShareMessage('Report sent to Branch Admin successfully.') }} />}</section>
}

export default FacultyExamReportsPage
