import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Search } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { getFacultyAssessmentStudentReport, listFacultyAssessmentReports } from '../services/examService'
import '../styles/FacultyExamReports.css'

const dateLabel = (value) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) : '-'

export default function FacultyAssessmentReportsPage({ embedded = false }) {
  const navigate = useNavigate(); const [summary, setSummary] = useState([]); const [report, setReport] = useState(null); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const loadSummary = () => { setLoading(true); listFacultyAssessmentReports().then(setSummary).catch((e) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(() => { loadSummary() }, [])
  const openReport = async (row) => { setLoading(true); setError(''); try { setReport(await getFacultyAssessmentStudentReport(row.course.id, row.batch.id, row.module.id)) } catch (e) { setError(e.message) } finally { setLoading(false) } }
  const visibleSummary = useMemo(() => { const query = search.trim().toLowerCase(); if (!query) return summary; return summary.filter((row) => [row.batch?.name, row.batch?.batchId].some((value) => String(value || '').toLowerCase().includes(query))) }, [search, summary])
  const pageSize = 5; const pageCount = Math.max(1, Math.ceil(visibleSummary.length / pageSize)); const pagedSummary = visibleSummary.slice((page - 1) * pageSize, page * pageSize)
  useEffect(() => { setPage(1) }, [search])
  useEffect(() => { if (page > pageCount) setPage(pageCount) }, [page, pageCount])
  if (report) return <section className={`exam-reports-page ${embedded ? 'exam-page-embedded' : ''}`}><button className="exam-back" onClick={() => setReport(null)}><ArrowLeft size={17} /> Assessment Reports</button><div className="exam-reports-header"><div><p className="exam-kicker">ASSESSMENT STUDENT REPORT</p><h1>{report.module.name}</h1><p>{report.course?.name || '-'} · {report.batch?.name || '-'}</p></div></div><div className="exam-report-meta"><div><span>Course Name</span><strong>{report.course?.name || '-'}</strong></div><div><span>Batch Name</span><strong>{report.batch?.name || '-'}</strong></div><div><span>Module Name</span><strong>{report.module.name}</strong></div><div><span>Total Assessments</span><strong>{report.totalAssessments}</strong></div></div><div className="exam-card exam-student-report-card"><div className="exam-card-heading"><h2>Student Assessment Report</h2></div>{report.assessments.length ? <div className="exam-report-table-wrap"><table><thead><tr><th className="exam-sticky-col">Student Name</th>{report.assessments.map((assessment) => <th key={assessment.id} title={`${assessment.assessmentName} · ${dateLabel(assessment.startDate)}`}><span className="exam-test-header">{assessment.assessmentName}</span><small>{assessment.totalMarks} marks</small></th>)}<th>Overall</th></tr></thead><tbody>{report.students.length ? report.students.map((student) => <tr key={student.studentId}><td className="exam-sticky-col"><strong>{student.studentName}</strong><small>{student.emailAddress || ''}</small></td>{report.assessments.map((assessment) => { const item = student.assessments[assessment.id]; const evaluated = item?.status === 'EVALUATED' && item.marksObtained != null; return <td key={assessment.id}>{evaluated ? <div className="assessment-report-cell"><strong>{item.marksObtained}/{item.totalMarks}</strong><span>{item.percentage.toFixed(2)}%</span></div> : item?.status === 'SUBMITTED' ? <span className="assessment-report-status">Submitted<br />Not Evaluated</span> : <span className="assessment-report-status">Not Submitted</span>}</td> })}<td>{student.overall.totalMarks ? <div className="assessment-report-cell"><strong>{student.overall.marksObtained}/{student.overall.totalMarks}</strong><span>{student.overall.percentage.toFixed(2)}%</span></div> : <span className="assessment-report-status">Not Evaluated</span>}</td></tr>) : <tr><td colSpan={report.assessments.length + 2} className="exam-empty">No students found for this batch.</td></tr>}</tbody></table></div> : <p className="exam-muted">No assessments available for this module.</p>}</div></section>
  return <section className={`exam-reports-page ${embedded ? 'exam-page-embedded' : ''}`}><div className="exam-reports-header"><div><p className="exam-kicker">FACULTY WORKSPACE</p><h1>Assessment Reports</h1><p>View assessment performance grouped by course, batch and module.</p></div></div><div className="exam-reports-filter-card assessment-reports-search-card"><label className="exam-reports-search"><span>Search Batch</span><div><Search size={16} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Batch name or batch ID" /></div></label></div>{error && <div className="exam-error">{error}</div>}<div className="exam-card exam-reports-table-card"><div className="exam-card-heading"><h2>Assessment Report Summary</h2></div>{loading ? <p className="exam-muted">Loading assessment reports...</p> : <><div className="exam-table-wrap"><table><thead><tr><th>Course Name</th><th>Batch Name</th><th>Module Name</th><th>Assessment Count</th><th>Actions</th></tr></thead><tbody>{pagedSummary.length ? pagedSummary.map((row) => <tr key={`${row.course.id}:${row.batch.id}:${row.module.id}`}><td>{row.course.name}</td><td>{row.batch.name}</td><td>{row.module.name}</td><td>{row.assessmentCount} Assessment{row.assessmentCount === 1 ? '' : 's'}</td><td><button className="exam-link" onClick={() => openReport(row)}>View Student Report</button></td></tr>) : <tr><td colSpan="5" className="exam-empty">No assessment reports found.</td></tr>}</tbody></table></div>{visibleSummary.length > pageSize && <div className="assessment-reports-pagination"><span>Showing {(page - 1) * pageSize + 1}-{Math.min(page * pageSize, visibleSummary.length)} of {visibleSummary.length}</span><div><button type="button" onClick={() => setPage((current) => current - 1)} disabled={page === 1}>Previous</button><strong>Page {page} of {pageCount}</strong><button type="button" onClick={() => setPage((current) => current + 1)} disabled={page === pageCount}>Next</button></div></div>}</>}</div></section>
}
