import { useEffect, useState } from 'react'
import { Plus, X } from 'lucide-react'
import { listFacultyExamCourses, listFacultyExamModules, listFacultyExamBatches, listFacultyAssessments, createFacultyAssessment, listAssessmentStudents, evaluateAssessmentSubmission } from '../services/examService'
import '../styles/ExamsPage.css'

const labelDate = (value) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) : '-'
const emptyForm = { assessmentName: '', courseId: '', moduleId: '', batchId: '', totalMarks: '', startDate: '', endDate: '', details: '' }

export default function FacultyAssessmentsPage({ embedded = false }) {
  const [rows, setRows] = useState([]); const [courses, setCourses] = useState([]); const [modules, setModules] = useState([]); const [batches, setBatches] = useState([]); const [form, setForm] = useState(emptyForm); const [fieldErrors, setFieldErrors] = useState({}); const [showCreate, setShowCreate] = useState(false); const [students, setStudents] = useState(null); const [selected, setSelected] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = () => listFacultyAssessments().then(setRows).catch((e) => setError(e.message))
  useEffect(() => { listFacultyExamCourses().then(setCourses).catch((e) => setError(e.message)); load() }, [])
  useEffect(() => { if (!form.courseId) { setModules([]); setBatches([]); return }; Promise.all([listFacultyExamModules(form.courseId), listFacultyExamBatches(form.courseId)]).then(([m, b]) => { setModules(m); setBatches(b) }).catch((e) => setError(e.message)) }, [form.courseId])
  const update = (key, value) => { setForm((current) => ({ ...current, [key]: value })); setFieldErrors((current) => ({ ...current, [key]: '' })) }
  const openCreate = () => { setForm(emptyForm); setFieldErrors({}); setError(''); setShowCreate(true) }
  const closeCreate = () => { setShowCreate(false); setForm(emptyForm); setFieldErrors({}); setError('') }
  const validate = () => { const next = {}; const required = { assessmentName: 'Assessment name is required', courseId: 'Course is required', moduleId: 'Module is required', batchId: 'Batch is required', totalMarks: 'Total marks is required', startDate: 'Start date and time is required', endDate: 'End date and time is required', details: 'Details / instructions are required' }; Object.entries(required).forEach(([key, message]) => { if (!String(form[key] || '').trim()) next[key] = message }); if (form.totalMarks && Number(form.totalMarks) <= 0) next.totalMarks = 'Total marks must be greater than 0'; if (form.startDate && form.endDate && new Date(form.endDate) <= new Date(form.startDate)) next.endDate = 'End date must be after start date'; setFieldErrors(next); return !Object.keys(next).length }
  const save = async (event) => { event.preventDefault(); if (!validate()) return; setSaving(true); setError(''); try { const created = await createFacultyAssessment(form); setRows((current) => [created, ...current]); setShowCreate(false); setForm(emptyForm); setFieldErrors({}) } catch (e) { setError(e.message) } finally { setSaving(false) } }
  const openStudents = async (row) => { setSelected(row); try { setStudents(await listAssessmentStudents(row.id)) } catch (e) { setError(e.message) } }
  const evaluate = async (item) => { const marks = window.prompt(`Marks obtained (out of ${selected.totalMarks})`, item.marksObtained ?? ''); if (marks === null) return; const feedback = window.prompt('Feedback', item.feedback || '') ?? ''; try { const result = await evaluateAssessmentSubmission(selected.id, item.student.id, { marksObtained: Number(marks), feedback }); setStudents((current) => current.map((entry) => entry.student.id === item.student.id ? { ...entry, ...result } : entry)) } catch (e) { setError(e.message) } }
  return <section className={`exam-page ${embedded ? 'exam-page-embedded' : ''}`}><header className="exam-page-header"><div><p className="exam-kicker">FACULTY WORKSPACE</p><h1>Assessments</h1><p>Create written assessments and evaluate batch submissions.</p></div><button className="exam-primary" onClick={openCreate}><Plus size={18} /> Create Assessment</button></header>{error && <div className="exam-error">{error}</div>}<div className="exam-card"><div className="exam-table-wrap"><table><thead><tr><th>Assessment Name</th><th>Course</th><th>Module</th><th>Batch</th><th>Marks</th><th>Start Date</th><th>End Date</th><th>Students</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td><strong>{row.assessmentName}</strong></td><td>{row.branchCourse?.name || '-'}</td><td>{row.module?.title || '-'}</td><td>{row.branchBatch?.batchName || '-'}</td><td>{row.totalMarks}</td><td>{labelDate(row.startDate)}</td><td>{labelDate(row.endDate)}</td><td><button className="exam-link" onClick={() => openStudents(row)}>View Students</button></td></tr>) : <tr><td colSpan="8" className="exam-empty">No assessments available</td></tr>}</tbody></table></div></div>
    {showCreate && <div className="exam-modal-backdrop"><form className="exam-modal assessment-modal" noValidate onSubmit={save}><div className="exam-card-heading assessment-modal-heading"><div><p className="exam-kicker">NEW ASSESSMENT</p><h2>Create Assessment</h2></div><button type="button" className="exam-icon-button" onClick={closeCreate}><X /></button></div><div className="exam-form-grid assessment-form-grid"><label>Assessment Name<input value={form.assessmentName} onChange={(e) => update('assessmentName', e.target.value)} /><small className="assessment-field-error">{fieldErrors.assessmentName}</small></label><label>Course<select value={form.courseId} onChange={(e) => { setForm({ ...emptyForm, courseId: e.target.value }); setFieldErrors((current) => ({ ...current, courseId: '', moduleId: '', batchId: '' })) }}><option value="">Select course</option>{courses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><small className="assessment-field-error">{fieldErrors.courseId}</small></label><label>Module<select value={form.moduleId} onChange={(e) => update('moduleId', e.target.value)}><option value="">Select module</option>{modules.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><small className="assessment-field-error">{fieldErrors.moduleId}</small></label><label>Batch<select value={form.batchId} onChange={(e) => update('batchId', e.target.value)}><option value="">Select batch</option>{batches.map((item) => <option key={item.id} value={item.id}>{item.batchName}</option>)}</select><small className="assessment-field-error">{fieldErrors.batchId}</small></label><label>Total Marks<input type="number" min="1" value={form.totalMarks} onChange={(e) => update('totalMarks', e.target.value)} /><small className="assessment-field-error">{fieldErrors.totalMarks}</small></label><label>Start Date<input type="datetime-local" value={form.startDate} onChange={(e) => update('startDate', e.target.value)} /><small className="assessment-field-error">{fieldErrors.startDate}</small></label><label>End Date<input type="datetime-local" value={form.endDate} onChange={(e) => update('endDate', e.target.value)} /><small className="assessment-field-error">{fieldErrors.endDate}</small></label><label className="exam-form-wide">Details / Instructions<textarea rows="4" value={form.details} onChange={(e) => update('details', e.target.value)} /><small className="assessment-field-error">{fieldErrors.details}</small></label></div><div className="question-builder-actions assessment-form-footer"><button type="button" className="exam-secondary" onClick={closeCreate}>Cancel</button><button className="exam-primary" disabled={saving}>{saving ? 'Creating...' : 'Create Assessment'}</button></div></form></div>}
    {selected && <div className="exam-modal-backdrop"><div className="exam-modal"><div className="exam-card-heading"><div><p className="exam-kicker">SUBMISSIONS</p><h2>{selected.assessmentName}</h2></div><button className="exam-icon-button" onClick={() => setSelected(null)}><X /></button></div><div className="exam-table-wrap"><table><thead><tr><th>Student Name</th><th>Submission Status</th><th>Submitted At</th><th>Marks</th><th>Percentage</th><th>Feedback</th><th /></tr></thead><tbody>{students?.map((item) => <tr key={item.student.id}><td>{item.student.studentName}</td><td>{item.status === 'NOT_SUBMITTED' ? 'Not Submitted' : item.status === 'EVALUATED' ? 'Evaluated' : 'Submitted'}</td><td>{item.submittedAt ? labelDate(item.submittedAt) : '-'}</td><td>{item.marksObtained ?? '-'}</td><td>{item.marksObtained != null ? `${((item.marksObtained / selected.totalMarks) * 100).toFixed(2)}%` : '-'}</td><td>{item.feedback || '-'}</td><td>{item.status !== 'NOT_SUBMITTED' && <button className="exam-link" onClick={() => evaluate(item)}>Evaluate</button>}</td></tr>)}</tbody></table></div></div></div>}
  </section>
}
