import { useEffect, useState } from 'react'
import { ArrowLeft, BookOpen, Plus, X } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { getFacultySkillAssignment, listFacultySkillAssignments, saveFacultySkillTopic } from '../services/facultySkillService'
import '../styles/FacultySkillsPage.css'

const formatDate = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'
const labelStatus = (value) => String(value || 'NOT_STARTED').replaceAll('_', ' ')
function StatusBadge({ value }) { return <span className={`faculty-skill-status status-${String(value || '').toLowerCase()}`}>{labelStatus(value)}</span> }
function ProgressBar({ value = 0 }) { return <div className="faculty-skill-progress"><span style={{ width: `${Math.max(0, Math.min(100, Number(value) || 0))}%` }} /><b>{value || 0}%</b></div> }

function LearningLog({ assignment, topic, onClose, onSaved }) {
  const [form, setForm] = useState({ status: topic.status, startDate: topic.startDate || '', expectedDate: topic.expectedDate || '', completedDate: topic.completedDate || '', learningSummary: topic.learningSummary || '', referenceType: topic.referenceType || '', referenceName: topic.referenceName || '', referenceUrl: topic.referenceUrl || '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  const submit = async (event) => { event.preventDefault(); setError(''); if (form.status !== 'NOT_STARTED' && (!form.startDate || !form.expectedDate)) return setError('Start date and expected completion date are required.'); if (form.status === 'COMPLETED' && !form.completedDate) return setError('Actual completed date is required for completed topics.'); setSaving(true); try { await onSaved(form) } catch (saveError) { setError(saveError.message || 'Unable to save learning log.') } finally { setSaving(false) } }
  return <div className="faculty-skill-modal-backdrop"><div className="faculty-skill-modal" role="dialog" aria-modal="true"><div className="faculty-skill-modal-head"><div><p className="faculty-skill-eyebrow">Learning Log</p><h2>{topic.topicName}</h2><p>{assignment.skill?.name}</p></div><button type="button" className="faculty-skill-icon-button" onClick={onClose}><X size={18} /></button></div><form className="faculty-skill-form" onSubmit={submit}><div className="faculty-skill-form-grid"><label>Start Date<input type="date" value={form.startDate} onChange={(event) => update('startDate', event.target.value)} disabled={topic.status === 'COMPLETED'} /></label><label>Expected Completion Date<input type="date" value={form.expectedDate} onChange={(event) => update('expectedDate', event.target.value)} disabled={topic.status === 'COMPLETED'} /></label></div><label>Status<select value={form.status} onChange={(event) => update('status', event.target.value)} disabled={topic.status === 'COMPLETED'}><option value="NOT_STARTED">Not Started</option><option value="IN_PROGRESS">In Progress</option><option value="COMPLETED">Completed</option></select></label><label>Actual Completed Date<input type="date" value={form.completedDate} onChange={(event) => update('completedDate', event.target.value)} disabled={topic.status === 'COMPLETED'} /></label><label>What Did You Learn?<textarea rows="4" value={form.learningSummary} onChange={(event) => update('learningSummary', event.target.value)} placeholder="Optional learning summary" /></label><div className="faculty-skill-form-grid"><label>Reference Type<select value={form.referenceType} onChange={(event) => update('referenceType', event.target.value)}><option value="">Select reference type</option>{['Self Learning', 'PDF / Document', 'Video / Online Resource', 'Other Faculty', 'Training / Workshop', 'Other'].map((type) => <option key={type}>{type}</option>)}</select></label><label>Reference Name<input value={form.referenceName} onChange={(event) => update('referenceName', event.target.value)} /></label></div><label>Reference Link<input type="url" value={form.referenceUrl} onChange={(event) => update('referenceUrl', event.target.value)} placeholder="https://..." /></label>{error ? <p className="faculty-skill-error">{error}</p> : null}<div className="faculty-skill-form-actions"><button type="button" className="faculty-skill-secondary-button" onClick={onClose}>Cancel</button><button type="submit" className="faculty-skill-primary-button" disabled={saving}>{saving ? 'Saving…' : 'Save Learning Log'}</button></div></form></div></div>
}

export function FacultySkillDevelopmentPage() {
  const navigate = useNavigate(); const { id } = useParams(); const [rows, setRows] = useState([]); const [assignment, setAssignment] = useState(null); const [topic, setTopic] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = async () => { setLoading(true); try { if (id) setAssignment(await getFacultySkillAssignment(id)); else { const response = await listFacultySkillAssignments(); setRows(response?.data || []) } } catch (loadError) { setError(loadError.message || 'Unable to load skill development.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [id])
  if (id && assignment) return <div className="faculty-skill-page"><button type="button" className="faculty-skill-back-button" onClick={() => navigate('/dashboard/faculty/skill-development')}><ArrowLeft size={17} /> Skill Development</button><header className="faculty-skill-page-head"><div><p className="faculty-skill-eyebrow">Faculty Dashboard</p><h1>{assignment.skill?.name}</h1><p>{formatDate(assignment.startDate)} to {formatDate(assignment.endDate)}</p></div><StatusBadge value={assignment.status} /></header><div className="faculty-skill-detail-card"><div><strong>Overall Progress</strong><ProgressBar value={assignment.progress} /></div><p>{assignment.completedTopics} of {assignment.topics?.length || 0} topics completed</p></div><div className="faculty-skill-table-wrap"><table><thead><tr><th>SI No.</th><th>Topic</th><th>Start Date</th><th>Expected Completion</th><th>Completed Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{assignment.topics?.map((item, index) => <tr key={item.id}><td>{index + 1}</td><td><strong>{item.topicName}</strong></td><td>{formatDate(item.startDate)}</td><td>{formatDate(item.expectedDate)}</td><td>{formatDate(item.completedDate)}</td><td><StatusBadge value={item.status} /></td><td><button type="button" className="faculty-skill-view-button" onClick={() => setTopic(item)}><Plus size={14} /> Add Learning Log</button></td></tr>)}</tbody></table></div>{topic ? <LearningLog assignment={assignment} topic={topic} onClose={() => setTopic(null)} onSaved={async (payload) => { await saveFacultySkillTopic(assignment.id, topic.id, payload); setTopic(null); await load() }} /> : null}</div>
  return <div className="faculty-skill-page"><header className="faculty-skill-page-head"><div><p className="faculty-skill-eyebrow">Faculty Dashboard</p><h1>Skill Development</h1><p>Track your assigned technology skills and learning progress.</p></div><BookOpen size={34} className="faculty-skill-page-icon" /></header>{error ? <div className="faculty-skill-error-panel">{error}</div> : null}<div className="faculty-skill-card-grid">{loading ? <div className="faculty-skill-empty-card">Loading assignments…</div> : rows.length === 0 ? <div className="faculty-skill-empty-card">No skill assignments have been assigned to you yet.</div> : rows.map((row) => <article className="faculty-skill-assignment-card" key={row.id}><div className="faculty-skill-assignment-card-head"><div><p>{row.skill?.name}</p><h2>{row.durationValue} month(s)</h2></div><StatusBadge value={row.status} /></div><div className="faculty-skill-assignment-card-meta"><span>{formatDate(row.startDate)} – {formatDate(row.endDate)}</span><span>{row.completedTopics}/{row.topics?.length || 0} topics</span></div><ProgressBar value={row.progress} /><button type="button" className="faculty-skill-primary-button" onClick={() => navigate(`/dashboard/faculty/skill-development/${row.id}`)}>View Topics</button></article>)}</div></div>
}
