import { useEffect, useMemo, useState } from 'react'
import { Search, RotateCcw } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { getFacultyExamReports, listFacultyExamBatches, listFacultyExamCourses, listFacultyExamModules } from '../services/examService'
import '../styles/FacultyExamReports.css'

export function FacultyExamReportsPage({ embedded = false }) {
  const navigate = useNavigate()
  const [courses, setCourses] = useState([]); const [modules, setModules] = useState([]); const [batches, setBatches] = useState([]); const [reports, setReports] = useState([])
  const [courseId, setCourseId] = useState(''); const [moduleId, setModuleId] = useState(''); const [batchId, setBatchId] = useState(''); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { listFacultyExamCourses().then(setCourses).catch((e) => setError(e.message)) }, [])
  useEffect(() => { if (!courseId) return; Promise.all([listFacultyExamModules(courseId), listFacultyExamBatches(courseId)]).then(([moduleItems, batchItems]) => { setModules(moduleItems); setBatches(batchItems) }).catch((e) => setError(e.message)) }, [courseId])
  useEffect(() => { getFacultyExamReports({ courseId, moduleId, batchId }).then(setReports).catch((e) => setError(e.message)).finally(() => setLoading(false)) }, [courseId, moduleId, batchId])
  const visibleReports = useMemo(() => { const query = search.trim().toLowerCase(); if (!query) return reports; return reports.filter((row) => [row.module?.title, row.batch?.name, row.batch?.batchId].some((value) => String(value || '').toLowerCase().includes(query))) }, [reports, search])
  const reset = () => { setCourseId(''); setModuleId(''); setBatchId(''); setSearch('') }
  const handleCourseChange = (value) => { setCourseId(value); setModuleId(''); setBatchId(''); setModules([]); setBatches([]) }
  return <section className={`exam-reports-page ${embedded ? 'exam-page-embedded' : ''}`}><div className="exam-reports-header"><div><p className="exam-kicker">FACULTY WORKSPACE</p><h1>Exam Reports</h1><p>View consolidated test performance by module and batch.</p></div></div><div className="exam-reports-filter-card"><label>Course<select value={courseId} onChange={(e) => handleCourseChange(e.target.value)}><option value="">All assigned courses</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</select></label><label>Module<select value={moduleId} onChange={(e) => setModuleId(e.target.value)} disabled={!courseId}><option value="">All modules</option>{modules.map((module) => <option key={module.id} value={module.id}>{module.title}</option>)}</select></label><label>Batch<select value={batchId} onChange={(e) => setBatchId(e.target.value)} disabled={!courseId}><option value="">All assigned batches</option>{batches.map((batch) => <option key={batch.id} value={batch.id}>{batch.batchName || batch.batchId}</option>)}</select></label><label className="exam-reports-search"><span>Search</span><div><Search size={16} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Module, batch or ID" /></div></label><button className="exam-secondary exam-reports-reset" onClick={reset}><RotateCcw size={15} /> Reset</button></div>{error && <div className="exam-error">{error}</div>}<div className="exam-card exam-reports-table-card"><div className="exam-card-heading"><h2>Consolidated reports</h2></div>{loading ? <p className="exam-muted">Loading exam reports...</p> : <div className="exam-table-wrap"><table><thead><tr><th>Module</th><th>Batch Name</th><th>Batch ID</th><th>Batch Timing</th><th>Tests</th><th>MCQs</th><th>Action</th></tr></thead><tbody>{visibleReports.length ? visibleReports.map((row) => <tr key={`${row.module.id}-${row.batch.id}`}><td><strong>{row.module.title}</strong></td><td>{row.batch.name || '-'}</td><td>{row.batch.batchId || '-'}</td><td>{row.batch.timing || '-'}</td><td>{row.testCount}</td><td>{row.mcqCount}</td><td><button className="exam-link" onClick={() => navigate(`/dashboard/faculty/exams/reports/${row.module.id}/${row.batch.id}`)}>View Student Report</button></td></tr>) : <tr><td colSpan="7" className="exam-empty">No exam reports found.</td></tr>}</tbody></table></div>}</div></section>
}

export default FacultyExamReportsPage
