import { useCallback, useEffect, useState } from 'react'
import { CalendarDays, Pencil, Plus, Trash2, X } from 'lucide-react'
import { createBranchHoliday, deleteBranchHoliday, listBranchHolidays, updateBranchHoliday } from '../services/branchHolidayService'
import '../styles/GeneralHolidayPage.css'

function displayDate(value) {
  const date = new Date(`${String(value || '').slice(0, 10)}T00:00:00`)
  return Number.isNaN(date.getTime()) ? value || '—' : date.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
}
export function GeneralHolidayPage() {
  const [holidays, setHolidays] = useState([]); const [form, setForm] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { setHolidays(await listBranchHolidays()) } catch (requestError) { setError(requestError?.message || 'Unable to load holidays.') } finally { setLoading(false) } }, [])
  useEffect(() => { const timer = window.setTimeout(() => { load() }, 0); return () => window.clearTimeout(timer) }, [load])
  async function save(event) { event.preventDefault(); setError(''); try { if (form.id) await updateBranchHoliday(form.id, form); else await createBranchHoliday(form); setForm(null); await load() } catch (requestError) { setError(requestError?.message || 'Unable to save holiday.') } }
  async function remove(item) { if (!window.confirm(`Remove ${item.name}?`)) return; try { await deleteBranchHoliday(item.id); await load() } catch (requestError) { setError(requestError?.message || 'Unable to remove holiday.') } }
  return <section className="branch-dashboard-section general-holidays-page"><div className="branch-dashboard-section-heading"><div><h2>General Holidays</h2><p>Manage holidays shown in faculty calendars.</p></div><button type="button" className="branch-dashboard-primary-action" onClick={() => setForm({ date: '', name: '' })}><Plus size={17} /> Add Holiday</button></div>{error ? <p className="branch-dashboard-error">{error}</p> : null}{loading ? <p>Loading holidays…</p> : <div className="branch-dashboard-table-shell"><table className="branch-dashboard-table"><thead><tr><th>Date</th><th>Holiday Name</th><th>Type</th><th>Status</th><th>Actions</th></tr></thead><tbody>{holidays.map((item) => <tr key={item.id}><td>{displayDate(item.holidayDate)}</td><td><strong>{item.name}</strong></td><td>General Holiday</td><td>{item.status}</td><td><button type="button" onClick={() => setForm({ id: item.id, date: item.holidayDate, name: item.name })}><Pencil size={16} /></button><button type="button" onClick={() => remove(item)}><Trash2 size={16} /></button></td></tr>)}{!holidays.length ? <tr><td colSpan={5}>No general holidays configured.</td></tr> : null}</tbody></table></div>}{form ? <div className="general-holiday-modal-backdrop"><form className="general-holiday-modal" onSubmit={save}><button type="button" onClick={() => setForm(null)}><X /></button><CalendarDays size={22} /><h3>{form.id ? 'Edit General Holiday' : 'Add General Holiday'}</h3><label>Holiday name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Date<input required type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><button type="submit">Save Holiday</button></form></div> : null}</section>
}
