import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import { getStudentTest, getStudentTestResult, listStudentTests, startStudentTest, submitStudentTest } from '../services/examService'
import '../styles/ExamsPage.css'
const dateLabel = (v) => v ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${v}T00:00:00`)) : '-'
export function StudentExamsPage() { const navigate = useNavigate(); const [tests, setTests] = useState([]); const [active, setActive] = useState(null); const [answers, setAnswers] = useState({}); const [result, setResult] = useState(null); const [error, setError] = useState(''); const refresh = async () => { try { const items = await listStudentTests(); setTests(items) } catch (e) { setError(e.message) } }; useEffect(() => { let mounted = true; listStudentTests().then((items) => { if (mounted) setTests(items) }).catch((e) => { if (mounted) setError(e.message) }); return () => { mounted = false } }, [])
  const open = async (row) => { try { setError(''); const detail = await getStudentTest(row.id); if (detail.status !== 'AVAILABLE') return setError(detail.status === 'EXPIRED' ? 'Test time expired.' : 'Test is not available yet.'); await startStudentTest(row.id); setActive(detail); setAnswers({}); } catch (e) { setError(e.message) } }
  const submit = async () => { if (!window.confirm('Are you sure you want to submit the test?')) return; try { await submitStudentTest(active.id, answers); setResult(await getStudentTestResult(active.id)); setActive(null); refresh() } catch (e) { setError(e.message) } }
  if (active) return <section className="exam-page"><header className="exam-page-header"><div><p className="exam-kicker">TEST IN PROGRESS</p><h1>{active.course?.name} · {active.module?.title}</h1><p>{active.totalQuestions} questions · {active.totalMarks} marks</p></div></header><div className="exam-card"><div className="student-question-list">{active.questions.map((q, i) => <article key={q.id}><h3>{i + 1}. {q.question}</h3>{['A','B','C','D'].map((letter) => <label key={letter}><input type="radio" name={q.id} checked={answers[q.id] === letter} onChange={() => setAnswers((a) => ({ ...a, [q.id]: letter }))} /> {letter}. {q[`option${letter}`]}</label>)}</article>)}</div><div className="student-test-actions"><button className="exam-secondary" onClick={() => { setActive(null); setAnswers({}); setError(''); refresh() }}>Cancel</button><button className="exam-primary exam-save" onClick={submit}>Submit Test</button></div></div></section>
  return <section className="exam-page"><header className="exam-page-header"><button className="exam-back" onClick={() => navigate('/student-new-dashboard')}><ArrowLeft size={18} /> Dashboard</button><div><p className="exam-kicker">STUDENT LEARNING</p><h1>Exam Test &amp; Assessment</h1><p>Only tests assigned to your enrolled batch are shown.</p></div></header>{error && <div className="exam-error">{error}</div>}{result && <div className="exam-card result-card"><h2>Test result</h2><p>Score: <strong>{result.obtainedMarks}/{result.totalMarks}</strong> · {Number(result.percentage || 0).toFixed(2)}%</p><p>Correct {result.correctAnswers} · Wrong {result.wrongAnswers} · Unanswered {result.unansweredQuestions}</p></div>}<div className="exam-card"><div className="exam-table-wrap"><table><thead><tr><th>Test</th><th>Course</th><th>Module</th><th>Date</th><th>Timing</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{tests.length ? tests.map((t) => <tr key={t.id}><td>MCQ Test</td><td>{t.course?.name}</td><td>{t.module?.title}</td><td>{dateLabel(t.testDate)}</td><td>{t.startTime} - {t.endTime}</td><td>{t.totalMarks}</td><td>{t.attempt?.status === 'SUBMITTED' ? 'Submitted' : t.status}</td><td><button className="exam-link" disabled={t.status !== 'AVAILABLE' || t.attempt?.status === 'SUBMITTED'} onClick={() => open(t)}>{t.attempt?.status === 'SUBMITTED' ? 'Completed' : t.status === 'AVAILABLE' ? 'Start Test' : t.status === 'EXPIRED' ? 'Expired' : 'Upcoming'}</button></td></tr>) : <tr><td colSpan="8" className="exam-empty">No tests available</td></tr>}</tbody></table></div></div></section> }
export default StudentExamsPage
