import { useEffect, useState } from 'react'
import { ArrowLeft } from 'lucide-react'
import { getAssessmentScreenshotBlob, getStudentAssessment, getStudentAssessmentSubmission, listStudentAssessments, submitStudentAssessment } from '../services/examService'
import '../styles/ExamsPage.css'

const dateTime = (value) => { if (!value) return '-'; const date = new Date(value); const day = String(date.getDate()).padStart(2, '0'); const month = new Intl.DateTimeFormat('en-GB', { month: 'short' }).format(date); const hour = date.getHours() % 12 || 12; const period = date.getHours() >= 12 ? 'PM' : 'AM'; return `${day} ${month} ${date.getFullYear()}, ${String(hour).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')} ${period}` }
const statusLabel = (value) => value === 'UPCOMING' ? 'Upcoming' : value === 'ACTIVE' ? 'Active' : 'Closed'

export default function StudentAssessmentsPage({ embedded = false }) {
  const [rows, setRows] = useState([]); const [active, setActive] = useState(null); const [response, setResponse] = useState(''); const [screenshot, setScreenshot] = useState(null); const [previewUrl, setPreviewUrl] = useState(''); const [submittedScreenshotUrl, setSubmittedScreenshotUrl] = useState(''); const [previewOpen, setPreviewOpen] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = () => listStudentAssessments().then(setRows).catch((e) => setError(e.message))
  useEffect(() => { load() }, [])
  const open = async (row) => { try { setError(''); const [detail, submission] = await Promise.all([getStudentAssessment(row.id), getStudentAssessmentSubmission(row.id)]); let screenshotSource = ''; if (submission?.screenshotUrl) { try { screenshotSource = await getAssessmentScreenshotBlob(submission.screenshotUrl) } catch { screenshotSource = '' } } setActive({ ...detail, submission }); setResponse(''); setScreenshot(null); setPreviewUrl(''); setSubmittedScreenshotUrl(screenshotSource) } catch (e) { setError(e.message) } }
  const chooseScreenshot = (event) => { const file = event.target.files?.[0]; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) { setError('Please choose a JPG, JPEG, PNG, or WEBP screenshot.'); event.target.value = ''; return } setError(''); setScreenshot(file); setPreviewUrl(URL.createObjectURL(file)) }
  const removeScreenshot = () => { setScreenshot(null); if (previewUrl) URL.revokeObjectURL(previewUrl); setPreviewUrl('') }
  const submit = async () => { if (!response.trim()) { setError('Assessment response is required.'); return } if (!screenshot) { setError('Attached screenshot is required.'); return } setSaving(true); setError(''); try { const result = await submitStudentAssessment(active.id, response.trim(), screenshot); const screenshotSource = result?.screenshotUrl ? await getAssessmentScreenshotBlob(result.screenshotUrl) : ''; setRows((current) => current.map((row) => row.id === active.id ? { ...row, submission: result } : row)); setActive((current) => ({ ...current, submission: result })); setSubmittedScreenshotUrl(screenshotSource); removeScreenshot() } catch (e) { setError(e.message) } finally { setSaving(false) } }
  if (active) { const submitted = Boolean(active.submission?.submittedAt); const evaluated = active.submission?.status === 'EVALUATED'; const screenshotUrl = submittedScreenshotUrl; return <section className={`exam-page ${embedded ? 'exam-page-embedded' : ''}`}><div className="exam-card"><div className="exam-card-heading"><div><button className="exam-back" onClick={() => setActive(null)}><ArrowLeft size={17} /> Assessments</button><h2>{active.assessmentName}</h2></div></div><div className="student-result-grid"><div><span>Course</span><strong>{active.branchCourse?.name}</strong></div><div><span>Module</span><strong>{active.module?.title}</strong></div><div><span>Total Marks</span><strong>{active.totalMarks}</strong></div><div><span>Start</span><strong>{dateTime(active.startDate)}</strong></div><div><span>End</span><strong>{dateTime(active.endDate)}</strong></div><div className="student-details-card"><span>Details / Instructions</span><strong>{active.details || 'No additional instructions.'}</strong></div></div>{submitted ? <div className="student-submitted-card"><h3>{evaluated ? 'Assessment Report' : 'Assessment submitted successfully.'}</h3><div><span>Assessment Response</span><p>{active.submission.response || '-'}</p></div>{screenshotUrl && <div><span>Attached Screenshot</span><img className="student-submission-image" src={screenshotUrl} alt="Attached screenshot" onClick={() => setPreviewOpen(true)} /></div>}<div><span>Submitted At</span><p>{dateTime(active.submission.submittedAt)}</p></div><div><span>Status</span><p>{evaluated ? 'Evaluated' : 'Pending Evaluation'}</p></div>{evaluated && <div className="student-result-score"><span>Marks Obtained</span><strong>{active.submission.marksObtained} / {active.totalMarks}</strong><b>{((active.submission.marksObtained / active.totalMarks) * 100).toFixed(2)}%</b><div><span>Faculty Review</span><p>{active.submission.feedback || 'No review provided.'}</p></div></div>}</div> : <><label className="exam-form-wide"><span>Assessment Response</span><textarea rows="10" value={response} onChange={(e) => setResponse(e.target.value)} placeholder="Enter your assessment response" /></label><label className="student-screenshot-field"><span>Attached Screenshot</span><input type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" onChange={chooseScreenshot} /><small>Choose Screenshot (JPG, JPEG, PNG, WEBP)</small>{previewUrl && <div className="student-screenshot-preview"><img src={previewUrl} alt="Screenshot preview" onClick={() => setPreviewOpen(true)} /><button type="button" className="exam-secondary" onClick={removeScreenshot}>Remove</button></div>}</label><button className="exam-primary" disabled={saving} onClick={submit}>{saving ? 'Submitting...' : 'Submit Assessment'}</button></>}</div></section> }
  return <section className={`exam-page ${embedded ? 'exam-page-embedded' : ''}`}><header className="exam-page-header"><div><p className="exam-kicker">STUDENT LEARNING</p><h1>Assessments</h1><p>Assessments assigned to your batch.</p></div></header>{error && <div className="exam-error">{error}</div>}<div className="exam-card"><div className="exam-table-wrap"><table><thead><tr><th>Assessment Name</th><th>Course</th><th>Module</th><th>Total Marks</th><th>Start Date</th><th>End Date</th><th>Status</th><th>Submission Status</th><th>Actions</th></tr></thead><tbody>{rows.length ? rows.map((row) => { const submitted = Boolean(row.submission?.submittedAt); const evaluated = row.submission?.status === 'EVALUATED'; const canStart = row.status === 'ACTIVE' && !submitted; return <tr key={row.id}><td><strong>{row.assessmentName}</strong></td><td>{row.branchCourse?.name}</td><td>{row.module?.title}</td><td>{row.totalMarks}</td><td>{dateTime(row.startDate)}</td><td>{dateTime(row.endDate)}</td><td>{statusLabel(row.status)}</td><td>{evaluated ? 'Evaluated' : submitted ? 'Submitted' : 'Not Submitted'}</td><td><button className="exam-link" disabled={!evaluated && !canStart} title={evaluated ? 'View assessment result' : !canStart ? (submitted ? 'Already submitted' : 'Assessment is not active') : 'Start assessment'} onClick={() => open(row)}>{evaluated ? 'View Result' : 'Start Assessment'}</button></td></tr> }) : <tr><td colSpan="9" className="exam-empty">No assessments available</td></tr>}</tbody></table></div></div></section>
}
