import { useEffect, useState } from 'react'
import { listStudentAcademicTests, getStudentAcademicTest, startStudentAcademicTest, submitStudentAcademicTest } from '../services/academicTestService'
import '../styles/StudentAcademicTestsPage.css'

const dateLabel = (value) => value ? new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) : '-'

export default function StudentAcademicTestsPage({ embedded = false }) {
  const [tests, setTests] = useState([]); const [active, setActive] = useState(null); const [answers, setAnswers] = useState({}); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = () => listStudentAcademicTests().then(setTests).catch((e) => setError(e.message || 'Unable to load Academic Tests.')).finally(() => setLoading(false))
  useEffect(() => { load() }, [])
  const start = async (test) => { try { setError(''); const detail = await getStudentAcademicTest(test.id); await startStudentAcademicTest(test.id); setActive(detail); setAnswers({}) } catch (e) { setError(e.message || 'This test is not available yet.') } }
  const submit = async () => { try { await submitStudentAcademicTest(active.id, answers); setActive(null); await load() } catch (e) { setError(e.message || 'Unable to submit test.') } }
  if (active) return <section className={`academic-student-page ${embedded ? 'academic-student-page-embedded' : ''}`}><div className="academic-student-test-heading"><h1>{active.testName} · {active.course?.name || '-'}</h1><p>{active.totalQuestions} Questions · {active.totalMarks} Marks · {active.startTime} - {active.endTime}</p></div><div className="academic-student-question-card">{active.questions.map((question, index) => <fieldset key={question.id}><legend>{index + 1}. {question.questionText} <small>{active.marksPerQuestion} marks</small></legend>{['A', 'B', 'C', 'D'].map((letter) => <label key={letter}><input type="radio" name={question.id} checked={answers[question.id] === letter} onChange={() => setAnswers((current) => ({ ...current, [question.id]: letter }))} />{letter}. {question[`option${letter}`]}</label>)}</fieldset>)}<button type="button" className="academic-student-primary" onClick={submit}>Submit Test</button></div></section>
  return <section className={`academic-student-page ${embedded ? 'academic-student-page-embedded' : ''}`}><header><p>EXAM CENTER & RESULT</p><h1>Academic Test</h1><span>Only tests assigned to your batch are shown.</span></header>{error && <div className="academic-student-error">{error}</div>}<div className="academic-student-card"><div className="academic-student-table-wrap"><table><thead><tr><th>Test Name</th><th>Course</th><th>Date</th><th>Timing</th><th>Total Questions</th><th>Total Marks</th><th>Action</th></tr></thead><tbody>{loading ? <tr><td colSpan="7">Loading Academic Tests...</td></tr> : tests.length ? tests.map((test) => <tr key={test.id}><td>{test.testName}</td><td>{test.course?.name || '-'}</td><td>{dateLabel(test.testDate)}</td><td>{test.startTime} - {test.endTime}</td><td>{test.totalQuestions}</td><td>{test.totalMarks}</td><td><button type="button" className="academic-student-link" disabled={test.submission?.status === 'SUBMITTED' || !['AVAILABLE'].includes(test.status)} onClick={() => start(test)}>{test.submission?.status === 'SUBMITTED' ? 'Completed' : test.status === 'AVAILABLE' ? 'Start Test' : test.status === 'EXPIRED' ? 'Expired' : 'Upcoming'}</button></td></tr>) : <tr><td colSpan="7">No Academic Tests available.</td></tr>}</tbody></table></div></div></section>
}
