import { useEffect, useState } from 'react'
import { ArrowLeft, X } from 'lucide-react'
import { getStudentAssessment, listStudentAssessments, submitStudentAssessment } from '../services/examService'
import '../styles/ExamsPage.css'

const dateTime = (value) => value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '-'
const statusLabel = (value) => value === 'UPCOMING' ? 'Upcoming' : value === 'ACTIVE' ? 'Active' : 'Closed'
export default function StudentAssessmentsPage({ embedded = false }) {
  const [rows, setRows] = useState([]); const [active, setActive] = useState(null); const [response, setResponse] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = () => listStudentAssessments().then(setRows).catch((e) => setError(e.message))
  useEffect(() => { load() }, [])
  const open = async (row) => { try { setError(''); setActive(await getStudentAssessment(row.id)); setResponse('') } catch (e) { setError(e.message) } }
  const submit = async () => { setSaving(true); try { const result = await submitStudentAssessment(active.id, response); setRows((current) => current.map((row) => row.id === active.id ? { ...row, submission: result } : row)); setActive(null) } catch (e) { setError(e.message) } finally { setSaving(false) } }
  if (active) return <section className={`exam-page ${embedded ? 'exam-page-embedded' : ''}`}><div className="exam-card"><div className="exam-card-heading"><div><button className="exam-back" onClick={() => setActive(null)}><ArrowLeft size={17} /> Assessments</button><h2>{active.assessmentName}</h2></div><button className="exam-icon-button" onClick={() => setActive(null)}><X /></button></div><div className="student-result-grid"><div><span>Course</span><strong>{active.branchCourse?.name}</strong></div><div><span>Module</span><strong>{active.module?.title}</strong></div><div><span>Total Marks</span><strong>{active.totalMarks}</strong></div><div><span>Start</span><strong>{dateTime(active.startDate)}</strong></div><div><span>End</span><strong>{dateTime(active.endDate)}</strong></div><div><span>Status</span><strong>{statusLabel(active.status)}</strong></div></div><p>{active.details || 'No additional instructions.'}</p>{active.submission?.status === 'EVALUATED' && <div className="student-result-score"><span>Result</span><strong>{active.submission.marksObtained} / {active.totalMarks}</strong><b>{((active.submission.marksObtained / active.totalMarks) * 100).toFixed(2)}%</b><p>{active.submission.feedback || 'No feedback provided.'}</p></div>}{active.submission?.status !== 'EVALUATED' && active.submission?.submittedAt && <div className="exam-muted">Submitted on {dateTime(active.submission.submittedAt)}. Awaiting evaluation.</div>}{active.status === 'ACTIVE' && !active.submission?.submittedAt && <><label className="exam-form-wide">Response / Submission<textarea rows="10" value={response} onChange={(e) => setResponse(e.target.value)} placeholder="Enter your assessment response" /></label><button className="exam-primary" disabled={saving} onClick={submit}>{saving ? 'Submitting...' : 'Submit Assessment'}</button></>}</div></section>
  return <section className={`exam-page ${embedded ? 'exam-page-embedded' : ''}`}><header className="exam-page-header"><div><p className="exam-kicker">STUDENT LEARNING</p><h1>Assessments</h1><p>Assessments assigned to your batch.</p></div></header>{error && <div className="exam-error">{error}</div>}<div className="exam-card"><div className="exam-table-wrap"><table><thead><tr><th>Assessment Name</th><th>Course</th><th>Module</th><th>Total Marks</th><th>Start Date</th><th>End Date</th><th>Status</th><th>Submission Status</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td><button className="exam-link" onClick={() => open(row)}>{row.assessmentName}</button></td><td>{row.branchCourse?.name}</td><td>{row.module?.title}</td><td>{row.totalMarks}</td><td>{dateTime(row.startDate)}</td><td>{dateTime(row.endDate)}</td><td>{statusLabel(row.status)}</td><td>{row.submission?.status === 'EVALUATED' ? 'Evaluated' : row.submission?.submittedAt ? 'Submitted' : 'Not Submitted'}</td></tr>) : <tr><td colSpan="8" className="exam-empty">No assessments available</td></tr>}</tbody></table></div></div></section>
}
